# Rake tasks for Curator. Real tasks are added during M1+.
#
# Planned (see features/implementation.md):
#   curator:seed_defaults
#   curator:ingest PATH=... KB=...
#   curator:reembed KB=...
#   curator:reingest DOCUMENT=...
#   curator:evaluations:export KB=... FORMAT=csv|json
#   curator:stats
#   curator:vacuum KB=...
#   curator:build_assets
