require "rails_helper"

# Phase 6 end-to-end smoke: the dummy app is the post-install output of
# `rails g curator:install` (regenerated by `bin/reset-dummy`). This spec
# verifies that against that installed state, migrating + seeding + booting
# the engine + hitting the mount point all wire together.
RSpec.describe "Curator engine smoke", type: :request do
  it "boots the engine, mounts at /curator, and responds non-5xx" do
    Curator::KnowledgeBase.seed_default!

    get "/curator"

    expect(response.status).to be < 500
    expect(response).to have_http_status(:ok)
    expect(response.body).to include("Curator")
  end

  it "serves the default KB after seeding" do
    Curator::KnowledgeBase.seed_default!

    kb = Curator::KnowledgeBase.find_by!(is_default: true)
    expect(kb.slug).to eq("default")
  end
end
